name: Lint PR

on:
  pull_request:
    types: [opened, reopened]
  push:
    
jobs:
  lint-pull-request:
    name: Lint PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Prettier check
        run: npx prettier --check src/* 
