name: NODE LTS
on: 
  push
jobs:
  install-node:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm run test
