name: Different Node versions

on: push

jobs:
  create-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Upload Cache
        uses: actions/upload-artifact@v2
        with:
          name: node-modules-cache
          path: ~/.npm

  test_schedule:
    needs: create-cache
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/*", 14.x, 16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Download Cache
        uses: actions/download-artifact@v3
        with:
          name: node-modules-cache

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
